# Site settings
title: Takumi Sakano - Portfolio & Blog
email: your.email@example.com
description: "Software Developer & Tech Enthusiast - Personal portfolio and blog"
baseurl: "/mypage" # the subpath of your site, e.g. /blog
url: "https://sakanotakumi.github.io" # the base hostname & protocol for your site
twitter_username: @sakanochii
github_username: sakanotakumi
linkedin_username: @sakanotakumi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: CV
    url: /cv/
  - title: Portfolio
    url: /portfolio/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Social links
social:
  - title: GitHub
    url: https://github.com/yourusername
    icon: fab fa-github
  - title: LinkedIn
    url: https://linkedin.com/in/yourusername
    icon: fab fa-linkedin
  - title: Twitter
    url: https://twitter.com/yourusername
    icon: fab fa-twitter
  - title: Email
    url: mailto:your.email@example.com
    icon: fas fa-envelope

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
